version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels: [dependencies, dotnet]

  - package-ecosystem: npm
    directory: /src/CampusCore.Web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels: [dependencies, web]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels: [dependencies, ci]
