using CampusCore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CampusCore.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("202608210001_InitialCreate")]
public sealed class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
CREATE SCHEMA IF NOT EXISTS campuscore;

CREATE TABLE campuscore."AspNetRoles" (
    "Id" text PRIMARY KEY,
    "Name" varchar(256), "NormalizedName" varchar(256), "ConcurrencyStamp" text);
CREATE UNIQUE INDEX "RoleNameIndex" ON campuscore."AspNetRoles" ("NormalizedName") WHERE "NormalizedName" IS NOT NULL;

CREATE TABLE campuscore."AspNetUsers" (
    "Id" text PRIMARY KEY, "DisplayName" text NOT NULL, "IsActive" boolean NOT NULL,
    "UserName" varchar(256), "NormalizedUserName" varchar(256), "Email" varchar(256), "NormalizedEmail" varchar(256),
    "EmailConfirmed" boolean NOT NULL, "PasswordHash" text, "SecurityStamp" text, "ConcurrencyStamp" text,
    "PhoneNumber" text, "PhoneNumberConfirmed" boolean NOT NULL, "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone, "LockoutEnabled" boolean NOT NULL, "AccessFailedCount" integer NOT NULL);
CREATE INDEX "EmailIndex" ON campuscore."AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON campuscore."AspNetUsers" ("NormalizedUserName") WHERE "NormalizedUserName" IS NOT NULL;

CREATE TABLE campuscore."AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "RoleId" text NOT NULL REFERENCES campuscore."AspNetRoles"("Id") ON DELETE CASCADE,
    "ClaimType" text, "ClaimValue" text);
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON campuscore."AspNetRoleClaims"("RoleId");
CREATE TABLE campuscore."AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "UserId" text NOT NULL REFERENCES campuscore."AspNetUsers"("Id") ON DELETE CASCADE,
    "ClaimType" text, "ClaimValue" text);
CREATE INDEX "IX_AspNetUserClaims_UserId" ON campuscore."AspNetUserClaims"("UserId");
CREATE TABLE campuscore."AspNetUserLogins" (
    "LoginProvider" varchar(128) NOT NULL, "ProviderKey" varchar(128) NOT NULL, "ProviderDisplayName" text, "UserId" text NOT NULL REFERENCES campuscore."AspNetUsers"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("LoginProvider", "ProviderKey"));
CREATE INDEX "IX_AspNetUserLogins_UserId" ON campuscore."AspNetUserLogins"("UserId");
CREATE TABLE campuscore."AspNetUserRoles" (
    "UserId" text NOT NULL REFERENCES campuscore."AspNetUsers"("Id") ON DELETE CASCADE,
    "RoleId" text NOT NULL REFERENCES campuscore."AspNetRoles"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId"));
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON campuscore."AspNetUserRoles"("RoleId");
CREATE TABLE campuscore."AspNetUserTokens" (
    "UserId" text NOT NULL REFERENCES campuscore."AspNetUsers"("Id") ON DELETE CASCADE,
    "LoginProvider" varchar(128) NOT NULL, "Name" varchar(128) NOT NULL, "Value" text,
    PRIMARY KEY ("UserId", "LoginProvider", "Name"));

CREATE TABLE campuscore."AcademicYears" (
    "Id" uuid PRIMARY KEY, "Name" text NOT NULL, "StartsOn" date NOT NULL, "EndsOn" date NOT NULL, "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX "IX_AcademicYears_Name" ON campuscore."AcademicYears"("Name");

CREATE TABLE campuscore."SchoolClasses" (
    "Id" uuid PRIMARY KEY, "Name" text NOT NULL, "SortOrder" integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX "IX_SchoolClasses_Name" ON campuscore."SchoolClasses"("Name");

CREATE TABLE campuscore."Students" (
    "Id" uuid PRIMARY KEY, "AdmissionNumber" varchar(64) NOT NULL, "FirstName" varchar(120) NOT NULL, "LastName" varchar(120) NOT NULL,
    "DateOfBirth" date NOT NULL, "Email" varchar(254), "Phone" varchar(40), "AddressLine" text, "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX "IX_Students_AdmissionNumber" ON campuscore."Students"("AdmissionNumber");

CREATE TABLE campuscore."StaffMembers" (
    "Id" uuid PRIMARY KEY, "EmployeeNumber" text NOT NULL, "FirstName" text NOT NULL, "LastName" text NOT NULL, "Email" text NOT NULL,
    "Phone" text, "JobTitle" text NOT NULL, "Status" integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX "IX_StaffMembers_EmployeeNumber" ON campuscore."StaffMembers"("EmployeeNumber");
CREATE UNIQUE INDEX "IX_StaffMembers_Email" ON campuscore."StaffMembers"("Email");

CREATE TABLE campuscore."Subjects" (
    "Id" uuid PRIMARY KEY, "Code" text NOT NULL, "Name" text NOT NULL, "MaximumMarks" numeric NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX "IX_Subjects_Code" ON campuscore."Subjects"("Code");

CREATE TABLE campuscore."GradeScales" (
    "Id" uuid PRIMARY KEY, "Name" text NOT NULL, "MinimumPercentage" numeric(5,2) NOT NULL, "MaximumPercentage" numeric(5,2) NOT NULL,
    "Grade" text NOT NULL, "Description" text, "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);

CREATE TABLE campuscore."InstitutionSettings" (
    "Id" uuid PRIMARY KEY, "InstitutionName" text NOT NULL, "Address" text, "TimeZoneId" text, "Locale" text NOT NULL, "DateFormat" text NOT NULL,
    "DefaultPageSize" integer NOT NULL, "AllowGuardianPortal" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);

CREATE TABLE campuscore."AuditLogs" (
    "Id" uuid PRIMARY KEY, "OccurredAtUtc" timestamp with time zone NOT NULL, "ActorUserId" varchar(450) NOT NULL,
    "Action" varchar(120) NOT NULL, "EntityType" varchar(120) NOT NULL, "EntityId" varchar(120) NOT NULL, "SafeMetadataJson" text, "CorrelationId" text);
CREATE INDEX "IX_AuditLogs_OccurredAtUtc" ON campuscore."AuditLogs"("OccurredAtUtc");

CREATE TABLE campuscore."Sections" (
    "Id" uuid PRIMARY KEY, "SchoolClassId" uuid NOT NULL REFERENCES campuscore."SchoolClasses"("Id") ON DELETE RESTRICT,
    "Name" text NOT NULL, "Capacity" integer NOT NULL, "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE INDEX "IX_Sections_SchoolClassId" ON campuscore."Sections"("SchoolClassId");

CREATE TABLE campuscore."Guardians" (
    "Id" uuid PRIMARY KEY, "StudentId" uuid NOT NULL REFERENCES campuscore."Students"("Id") ON DELETE CASCADE,
    "Name" varchar(200) NOT NULL, "Relationship" varchar(80) NOT NULL, "Email" text, "Phone" text, "IsPrimary" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE INDEX "IX_Guardians_StudentId" ON campuscore."Guardians"("StudentId");

CREATE TABLE campuscore."Enrollments" (
    "Id" uuid PRIMARY KEY, "StudentId" uuid NOT NULL REFERENCES campuscore."Students"("Id") ON DELETE RESTRICT,
    "AcademicYearId" uuid NOT NULL REFERENCES campuscore."AcademicYears"("Id") ON DELETE RESTRICT,
    "SectionId" uuid NOT NULL REFERENCES campuscore."Sections"("Id") ON DELETE RESTRICT,
    "EnrolledOn" date NOT NULL, "Status" integer NOT NULL, "RollNumber" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX "IX_Enrollments_StudentId_AcademicYearId" ON campuscore."Enrollments"("StudentId", "AcademicYearId");
CREATE INDEX "IX_Enrollments_AcademicYearId" ON campuscore."Enrollments"("AcademicYearId");
CREATE INDEX "IX_Enrollments_SectionId" ON campuscore."Enrollments"("SectionId");

CREATE TABLE campuscore."AttendanceRecords" (
    "Id" uuid PRIMARY KEY, "StudentId" uuid NOT NULL REFERENCES campuscore."Students"("Id") ON DELETE CASCADE,
    "Date" date NOT NULL, "Status" integer NOT NULL, "Note" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX "IX_AttendanceRecords_StudentId_Date" ON campuscore."AttendanceRecords"("StudentId", "Date");

CREATE TABLE campuscore."LeaveRequests" (
    "Id" uuid PRIMARY KEY, "StudentId" uuid NOT NULL REFERENCES campuscore."Students"("Id") ON DELETE CASCADE,
    "StartsOn" date NOT NULL, "EndsOn" date NOT NULL, "Reason" text NOT NULL, "Status" integer NOT NULL, "DecisionNote" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE INDEX "IX_LeaveRequests_StudentId" ON campuscore."LeaveRequests"("StudentId");

CREATE TABLE campuscore."Marks" (
    "Id" uuid PRIMARY KEY, "StudentId" uuid NOT NULL REFERENCES campuscore."Students"("Id") ON DELETE CASCADE,
    "SubjectId" uuid NOT NULL REFERENCES campuscore."Subjects"("Id") ON DELETE RESTRICT,
    "AcademicYearId" uuid NOT NULL REFERENCES campuscore."AcademicYears"("Id") ON DELETE RESTRICT,
    "AssessmentName" text NOT NULL, "Score" numeric(8,2) NOT NULL, "MaximumScore" numeric(8,2) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE INDEX "IX_Marks_StudentId" ON campuscore."Marks"("StudentId");
CREATE INDEX "IX_Marks_SubjectId" ON campuscore."Marks"("SubjectId");
CREATE INDEX "IX_Marks_AcademicYearId" ON campuscore."Marks"("AcademicYearId");

CREATE TABLE campuscore."TimetableEntries" (
    "Id" uuid PRIMARY KEY, "SectionId" uuid NOT NULL REFERENCES campuscore."Sections"("Id") ON DELETE CASCADE,
    "SubjectId" uuid NOT NULL REFERENCES campuscore."Subjects"("Id") ON DELETE CASCADE,
    "StaffMemberId" uuid REFERENCES campuscore."StaffMembers"("Id"), "DayOfWeek" integer NOT NULL,
    "StartsAt" time without time zone NOT NULL, "EndsAt" time without time zone NOT NULL, "Room" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE INDEX "IX_TimetableEntries_SectionId_DayOfWeek_StartsAt" ON campuscore."TimetableEntries"("SectionId", "DayOfWeek", "StartsAt");
CREATE INDEX "IX_TimetableEntries_SubjectId" ON campuscore."TimetableEntries"("SubjectId");
CREATE INDEX "IX_TimetableEntries_StaffMemberId" ON campuscore."TimetableEntries"("StaffMemberId");

CREATE TABLE campuscore."Announcements" (
    "Id" uuid PRIMARY KEY, "Title" text NOT NULL, "Body" text NOT NULL, "Audience" integer NOT NULL,
    "PublishAtUtc" timestamp with time zone NOT NULL, "ExpiresAtUtc" timestamp with time zone,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);

CREATE TABLE campuscore."AnnouncementAttachments" (
    "Id" uuid PRIMARY KEY, "AnnouncementId" uuid NOT NULL REFERENCES campuscore."Announcements"("Id") ON DELETE CASCADE,
    "FileName" text NOT NULL, "StoredName" varchar(200) NOT NULL, "ContentType" text NOT NULL, "SizeBytes" bigint NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL, "UpdatedAtUtc" timestamp with time zone NOT NULL);
CREATE INDEX "IX_AnnouncementAttachments_AnnouncementId" ON campuscore."AnnouncementAttachments"("AnnouncementId");
""");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP SCHEMA IF EXISTS campuscore CASCADE;");
    }
}
